# Generated by Django 2.0 on 2018-09-26 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_name', models.CharField(max_length=200)),
                ('optional_keywords', models.TextField(max_length=200)),
                ('required_keywords', models.TextField(max_length=200)),
                ('excluded_keywords', models.TextField(max_length=200)),
            ],
            options={
                'db_table': 'Keyword',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StatusID', models.CharField(max_length=45)),
                ('Content', models.TextField()),
                ('CreatedAt', models.DateTimeField()),
                ('ResharerCount', models.IntegerField()),
                ('Source', models.CharField(max_length=45)),
                ('Sentiment', models.IntegerField()),
                ('KeywordID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMM.Keyword')),
            ],
            options={
                'db_table': 'Post',
            },
        ),
        migrations.CreateModel(
            name='PostUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.CharField(max_length=60)),
                ('DisplayName', models.CharField(max_length=45)),
                ('DisplayPicture', models.CharField(max_length=1024)),
                ('TotalLikes', models.IntegerField()),
                ('TotalPosts', models.IntegerField()),
                ('FollowingCount', models.IntegerField()),
                ('FollowerCount', models.IntegerField()),
                ('PostReshareCount', models.IntegerField()),
            ],
            options={
                'db_table': 'PostUser',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=500)),
                ('email', models.EmailField(blank=True, max_length=30)),
                ('phone_no', models.BinaryField(blank=True, max_length=14)),
                ('country', models.CharField(blank=True, max_length=20)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('company_name', models.CharField(blank=True, max_length=30)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('company_size', models.CharField(blank=True, max_length=30)),
                ('avatar', models.ImageField(upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resharer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PostID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMM.Post')),
                ('PostUserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMM.PostUser')),
            ],
            options={
                'db_table': 'Resharer',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='PostUserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMM.PostUser'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='Userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMM.Profile'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='keyword',
            order_with_respect_to='Userid',
        ),
    ]
