# Generated by Django 2.0 on 2018-09-27 10:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_name', models.CharField(max_length=200)),
                ('optional_keywords', models.TextField(max_length=200, null=True)),
                ('required_keywords', models.TextField(max_length=200, null=True)),
                ('excluded_keywords', models.TextField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'Keyword',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StatusID', models.CharField(max_length=45)),
                ('Content', models.TextField()),
                ('CreatedAt', models.DateTimeField()),
                ('ResharerCount', models.IntegerField()),
                ('Source', models.CharField(max_length=45)),
                ('Sentiment', models.IntegerField(blank=True, null=True)),
                ('Keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMM.Keyword')),
            ],
            options={
                'db_table': 'Post',
            },
        ),
        migrations.CreateModel(
            name='PostUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.CharField(max_length=60)),
                ('DisplayName', models.CharField(max_length=45)),
                ('DisplayPicture', models.CharField(max_length=1024)),
                ('TotalLikes', models.IntegerField(null=True)),
                ('TotalPosts', models.IntegerField(null=True)),
                ('FollowingCount', models.IntegerField(null=True)),
                ('FollowerCount', models.IntegerField(null=True)),
                ('PostReshareCount', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'PostUser',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=500)),
                ('email', models.EmailField(blank=True, max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('country', models.CharField(blank=True, max_length=20)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('company_name', models.CharField(blank=True, max_length=30)),
                ('company_size', models.CharField(blank=True, max_length=30)),
                ('avatar', models.ImageField(upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resharer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMM.Post')),
                ('PostUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMM.PostUser')),
            ],
            options={
                'db_table': 'Resharer',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='PostUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMM.PostUser'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMM.Profile'),
        ),
    ]
