# Generated by Django 2.0 on 2018-09-19 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SMM', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='Post',
        ),
        migrations.AlterModelTable(
            name='postuser',
            table='PostUser',
        ),
        migrations.AlterModelTable(
            name='resharer',
            table='Resharer',
        ),
    ]
