# Generated by Django 2.0 on 2018-09-26 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SMM', '0002_auto_20180926_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
