# Generated by Django 2.0 on 2018-09-24 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SMM', '0003_auto_20180919_0536'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table=None,
        ),
    ]
