# Generated by Django 2.0 on 2018-09-24 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SMM', '0004_auto_20180924_0517'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='keyword',
            order_with_respect_to=None,
        ),
    ]
