# Generated by Django 2.0 on 2018-09-25 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMM', '0005_auto_20180924_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyword',
            old_name='Userid',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='KeywordID',
            new_name='Keyword',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='PostUserID',
            new_name='PostUser',
        ),
        migrations.RenameField(
            model_name='resharer',
            old_name='PostID',
            new_name='Post',
        ),
        migrations.RenameField(
            model_name='resharer',
            old_name='PostUserID',
            new_name='PostUser',
        ),
        migrations.AlterField(
            model_name='keyword',
            name='excluded_keywords',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='optional_keywords',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='required_keywords',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='postuser',
            name='FollowerCount',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='postuser',
            name='FollowingCount',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='postuser',
            name='PostReshareCount',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='postuser',
            name='TotalLikes',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='postuser',
            name='TotalPosts',
            field=models.IntegerField(blank=True),
        ),
    ]
