# Generated by Django 2.0 on 2018-09-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMM', '0006_auto_20180925_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postuser',
            name='FollowerCount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postuser',
            name='FollowingCount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postuser',
            name='PostReshareCount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postuser',
            name='TotalLikes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postuser',
            name='TotalPosts',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
