# Generated by Django 2.0 on 2018-09-25 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMM', '0007_auto_20180925_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Sentiment',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
