# Generated by Django 2.0 on 2018-09-25 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMM', '0009_auto_20180925_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postuser',
            name='FollowerCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='postuser',
            name='FollowingCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='postuser',
            name='PostReshareCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='postuser',
            name='TotalLikes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='postuser',
            name='TotalPosts',
            field=models.IntegerField(null=True),
        ),
    ]
