# Generated by Django 2.0 on 2018-09-25 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SMM', '0011_auto_20180925_0638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='mail_confirmed',
            new_name='email_confirmed',
        ),
    ]
